version: 2

jobs:
  build:
    docker:
    - image: node:9
    working_directory: ~/repo
    steps:
    - checkout
    - run: cd client
    - run: npm install 
    - run: tar -cf dist.tar dist
    - store_artifacts:
        path: ~/repo/dist.tar
